project_name: baton-broadcom-sac
builds:
  - binary: baton-broadcom-sac
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/baton-broadcom-sac
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/conductorone/baton-broadcom-sac:{{ .Version }}-amd64"
      - "ghcr.io/conductorone/baton-broadcom-sac:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton-broadcom-sac"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/conductorone/baton-broadcom-sac"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/conductorone/baton-broadcom-sac:{{ .Version }}-arm64"
      - "ghcr.io/conductorone/baton-broadcom-sac:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=baton-broadcom-sac"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/conductorone/baton-broadcom-sac"
docker_manifests:
  - name_template: ghcr.io/conductorone/baton-broadcom-sac:{{ .Version }}
    image_templates:
      - ghcr.io/conductorone/baton-broadcom-sac:{{ .Version }}-amd64
      - ghcr.io/conductorone/baton-broadcom-sac:{{ .Version }}-arm64
  - name_template: ghcr.io/conductorone/baton-broadcom-sac:latest
    image_templates:
      - ghcr.io/conductorone/baton-broadcom-sac:latest-amd64
      - ghcr.io/conductorone/baton-broadcom-sac:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true